%%% Do not modify this file, it is automatically generated by abnfc.
%%% All changes will be lost when it is regenerated.
%%% Generated by abnfc_gen on 2012-01-25 18:56:43

-module(rfc4234_core).

-export(['ALPHA'/0, 'BIT'/0, 'CHAR'/0, 'CR'/0, 'CRLF'/0,
         'CTL'/0, 'DIGIT'/0, 'DQUOTE'/0, 'HEXDIG'/0, 'HTAB'/0,
         'LF'/0, 'LWSP'/0, 'OCTET'/0, 'SP'/0, 'VCHAR'/0, 'WSP'/0,
         decode/2]).

-include("rfc4234_core.hrl").

decode('ALPHA', Str) -> ('ALPHA'())(Str);
decode('BIT', Str) -> ('BIT'())(Str);
decode('CHAR', Str) -> ('CHAR'())(Str);
decode('CR', Str) -> ('CR'())(Str);
decode('CRLF', Str) -> ('CRLF'())(Str);
decode('CTL', Str) -> ('CTL'())(Str);
decode('DIGIT', Str) -> ('DIGIT'())(Str);
decode('DQUOTE', Str) -> ('DQUOTE'())(Str);
decode('HEXDIG', Str) -> ('HEXDIG'())(Str);
decode('HTAB', Str) -> ('HTAB'())(Str);
decode('LF', Str) -> ('LF'())(Str);
decode('LWSP', Str) -> ('LWSP'())(Str);
decode('OCTET', Str) -> ('OCTET'())(Str);
decode('SP', Str) -> ('SP'())(Str);
decode('VCHAR', Str) -> ('VCHAR'())(Str);
decode('WSP', Str) -> ('WSP'())(Str).

'ALPHA'() ->
    fun ([C | Tl]) when (C >= 65) and (C =< 90) ->
            {ok, C, Tl};
        ([C | Tl]) when (C >= 97) and (C =< 122) -> {ok, C, Tl};
        (_) -> fail
    end.

'BIT'() ->
    fun ([C | Tl]) when (C >= 48) and (C =< 49) ->
            {ok, C, Tl};
        (_) -> fail
    end.

'CHAR'() ->
    fun ([C | Tl]) when (C >= 1) and (C =< 127) ->
            {ok, C, Tl};
        (_) -> fail
    end.

'CR'() ->
    fun ([13 | Tl]) -> {ok, 13, Tl};
        (_) -> fail
    end.

'CRLF'() ->
    '__alt'(['LF'(), '__seq'(['CR'(), 'LF'()])]).

'CTL'() ->
    fun ([C | Tl]) when (C >= 0) and (C =< 31) ->
            {ok, C, Tl};
        ([C | Tl]) when C == 127 -> {ok, C, Tl};
        (_) -> fail
    end.

'DIGIT'() ->
    fun ([C | Tl]) when (C >= 48) and (C =< 57) ->
            {ok, C, Tl};
        (_) -> fail
    end.

'DQUOTE'() ->
    fun ([34 | Tl]) -> {ok, 34, Tl};
        (_) -> fail
    end.

'HEXDIG'() ->
    '__alt'(['DIGIT'(),
             fun ([C | Tl]) when C == 97 -> {ok, C, Tl};
                 ([C | Tl]) when C == 65 -> {ok, C, Tl};
                 (_) -> fail
             end,
             fun ([C | Tl]) when C == 98 -> {ok, C, Tl};
                 ([C | Tl]) when C == 66 -> {ok, C, Tl};
                 (_) -> fail
             end,
             fun ([C | Tl]) when C == 99 -> {ok, C, Tl};
                 ([C | Tl]) when C == 67 -> {ok, C, Tl};
                 (_) -> fail
             end,
             fun ([C | Tl]) when C == 100 -> {ok, C, Tl};
                 ([C | Tl]) when C == 68 -> {ok, C, Tl};
                 (_) -> fail
             end,
             fun ([C | Tl]) when C == 101 -> {ok, C, Tl};
                 ([C | Tl]) when C == 69 -> {ok, C, Tl};
                 (_) -> fail
             end,
             fun ([C | Tl]) when C == 102 -> {ok, C, Tl};
                 ([C | Tl]) when C == 70 -> {ok, C, Tl};
                 (_) -> fail
             end]).

'HTAB'() ->
    fun ([9 | Tl]) -> {ok, 9, Tl};
        (_) -> fail
    end.

'LF'() ->
    fun ([10 | Tl]) -> {ok, 10, Tl};
        (_) -> fail
    end.

'LWSP'() ->
    '__repeat'(0, infinity,
               '__alt'(['WSP'(), '__seq'(['CRLF'(), 'WSP'()])])).

'OCTET'() ->
    fun ([C | Tl]) when (C >= 0) and (C =< 255) ->
            {ok, C, Tl};
        (_) -> fail
    end.

'SP'() ->
    fun ([32 | Tl]) -> {ok, 32, Tl};
        (_) -> fail
    end.

'VCHAR'() ->
    fun ([C | Tl]) when (C >= 33) and (C =< 126) ->
            {ok, C, Tl};
        (_) -> fail
    end.

'WSP'() -> '__alt'(['SP'(), 'HTAB'()]).

'__alt'(Ps) -> fun (T) -> '__do_alt'(Ps, T) end.

'__do_alt'([P | Ps], T) ->
    case P(T) of
      {ok, _R, _T1} = Res -> Res;
      fail -> '__do_alt'(Ps, T)
    end;
'__do_alt'([], _) -> fail.

'__repeat'(Min, Max, P) -> '__repeat'(Min, Max, P, 0).

'__repeat'(Min, Max, P, Found) ->
    fun (T) -> '__do_repeat'(Min, Max, P, Found, T) end.

'__do_repeat'(Min, Max, P, Found, T) ->
    case P(T) of
      {ok, R1, T1} ->
          case '__do_repeat'(Min, Max, P, Found + 1, T1) of
            {ok, R2, T2} -> {ok, [R1 | R2], T2};
            fail when Found >= Min -> {ok, [R1], T1};
            fail -> fail
          end;
      fail when Found >= Min -> {ok, [], T};
      fail -> fail
    end.

'__seq'(Ps) -> fun (T) -> '__do_seq'(Ps, T) end.

'__do_seq'([P | Ps], T) ->
    case P(T) of
      {ok, R1, T1} ->
          case '__do_seq'(Ps, T1) of
            {ok, R2, T2} -> {ok, [R1 | R2], T2};
            fail -> fail
          end;
      fail -> fail
    end;
'__do_seq'([], T) -> {ok, [], T}.
